export default {
    email: /^([0-9a-zA-Z]([-_\\.]*[0-9a-zA-Z]+)*)@([0-9a-zA-Z]([-_\\.]*[0-9a-zA-Z]+)*)[\\.]([a-zA-Z]{2,9})$/,
    numeric: /^[0-9]*\.?[0-9]+$/,
    all_numeric: /^[\-+]?[0-9]*\.?[0-9]+$/,
    integer: /^[0-9]+$/,
    fieldSpace : /^\S/,
    alpha: /^[A-Z]+$/i,
    alpha_spaces: /^[A-Z-&' ]+$/i,
    alpha_numeric: /^[A-Z0-9]+$/i,
    alpha_numeric_spaces: /^[A-Z0-9 ]+$/i,
    alpha_numeric_spaces_no_white: /^[A-Z0-9]+( [A-Z0-9]+)*$/i,
    alpha_spaces_no_white: /^[A-Z]+( [A-Z]+)*$/i,
    single_address_line: /^[A-Za-z0-9\/,. ]+(?:[\/,.:;-][A-Za-z0-9\/,. ]+)*$/,
    password: /^\S/,
    strong_password: /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-+`~]).{8,}$/,
    strong_password_no_special: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d\w\W]{8,}$/,
    number_with_decimal: /^[0-9]+(\.[0-9]{1,2})?$/,
    special_char: /[ !@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/,
    image_types: ["image/png", "image/jpg", "image/jpeg", "image/jp2", "image/jpx", "image/jpm", "image/tiff"],
}